### PR TITLE
Fix: `copilot seat details` schema fixed

### PR DESCRIPTION
**Pull request by jecluis**
While parsing OpenAPI spec for 2022-11-28:

```
  codegen/parser/utils.py", line 105, in merge_dict
    del old[key]
        ~~~^^^^^
  KeyError: 'enum'
```

Signed-off-by: Joao Eduardo Luis \<joao@1e3ms.io>

P.S.: This was hit while running `python -m codegen` on the current master branch (620e08f26274c6fd51339078c4fbfd29c80e702f), which was surprising. I'm not ruling out this might be a problem with my environment, but I suspect this might be a corner case somewhere with the schema.

### CODE REVIEW

**Comment by yanyongyu** [comment]
This is caused by schema update made by GitHub. This should be fixed in the schema override part in the `pyproject.toml` file.

**Comment by jecluis** [comment]
> This is caused by schema update made by GitHub. This should be fixed in the schema override part in the `pyproject.toml` file.

I suspected that could be the case as well. Any idea which schema bit is triggering this? Happy to open a PR to address it.

Also, feel free to close this one if not the right path to address the problem :)

**Comment by yanyongyu** [comment]
It seems this is caused by https://github.com/yanyongyu/githubkit/blob/620e08f26274c6fd51339078c4fbfd29c80e702f/pyproject.toml#L226-L231

**Review by yanyongyu — APPROVED** [review]
It seems codegen is successful now 👍🏻 (My gh codespace OOM again and again)

**Comment by jecluis** [comment]
@yanyongyu thank you for all your work on this!

**Pull request merged**
